##### Consider the below code to answer further questions:
```
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```
##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of the variables `list_` and `array_list`. The variable `list_` is a Python list, while `array_list` is a NumPy array. 

##### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [12]:
# To print the data types of both variables, we can use the `type()` function in Python. Here's the code to accomplish that:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


##### Q3. Considering the following changes in the variable, array_list:
```
array_list = np.array(object = list_, dtype = int)
```
###### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes, there will be a difference in the data type of the elements present in the variables `list_` and `array_list` after specifying `dtype=int` during array creation. The elements in `list_` are originally strings, while the elements in `array_list` will be converted to integers based on the specified data type.

In [16]:
# To print the data types of each element in `list_` and `array_list`, we can iterate over the elements and use the `type()`
# function. Here's the code to accomplish that:

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


##### Consider the below code to answer further questions:
```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```
##### Q4. Write a code to find the following characteristics of variable, num_array:
```
(i) shape
(ii) size
```

In [21]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# (ii) Find the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [24]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])